# Generated by Django 4.2.6 on 2023-10-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=2023),
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
    ]
